name: SpringBoot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push user-service
      run: |
        docker build -t your-dockerhub-username/user-service:latest -f user-service/Dockerfile .
        docker push your-dockerhub-username/user-service:latest
    
    - name: Build and push department-service
      run: |
        docker build -t your-dockerhub-username/department-service:latest -f department-service/Dockerfile .
        docker push your-dockerhub-username/department-service:latest
    
    - name: Build and push cloud-config-server
      run: |
        docker build -t your-dockerhub-username/cloud-config-server:latest -f cloud-config-server/Dockerfile .
        docker push your-dockerhub-username/cloud-config-server:latest
    
    - name: Build and push cloud-gateway
      run: |
        docker build -t your-dockerhub-username/cloud-gateway:latest -f cloud-gateway/Dockerfile .
        docker push your-dockerhub-username/cloud-gateway:latest
    
    - name: Build and push hystrix-dashboard
      run: |
        docker build -t your-dockerhub-username/hystrix-dashboard:latest -f hystrix-dashboard/Dockerfile .
        docker push your-dockerhub-username/hystrix-dashboard:latest
    
    - name: Build and push service-registry
      run: |
        docker build -t your-dockerhub-username/service-registry:latest -f service-registry/Dockerfile .
        docker push your-dockerhub-username/service-registry:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/